CREATE SEQUENCE compteur
START WITH 1
INCREMENT BY 1;


 CREATE TABLE "CATEGORIES" 
   ("IDCATEG" Integer PRIMARY KEY, 
	"NOMDECATEGORIE" VARCHAR2(100 CHAR), 
	"DESCRIPTION" CLOB
   );

INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'dui','Donec,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'consequat','ut aliquam iaculis, lacus pede sagittis augue,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'at,','Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'metus.','venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'lacus','Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'id','Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'pellentesque,','et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'magna.','quam. Curabitur vel lectus. Cum sociis natoque penatibus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ipsum','cursus et, magna. Praesent interdum');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'dignissim','blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'tempus','laoreet ipsum. Curabitur consequat,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Ut','ullamcorper viverra. Maecenas iaculis aliquet diam.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'lorem','elit, pretium et, rutrum');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'est.','at, egestas a, scelerisque');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'pede,','ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'convallis,','In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ac','est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'euismod','ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'dolor','ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'mi,','Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ut,','tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Lorem','semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'metus','Quisque');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'non','a, dui.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ornare','lectus, a sollicitudin');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'orci','vitae,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'mollis','non enim commodo hendrerit. Donec porttitor tellus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'venenatis','nec tempus mauris erat eget');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ac','non quam. Pellentesque');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Aliquam','erat vitae risus. Duis a');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Suspendisse','bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'iaculis','ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'augue','lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'cursus','pede blandit congue. In scelerisque scelerisque dui.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'montes,','egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'enim.','libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'tempor','Morbi sit amet massa. Quisque porttitor eros');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'semper','diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'elementum','erat eget ipsum. Suspendisse sagittis. Nullam');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Nulla','et nunc. Quisque ornare tortor at risus. Nunc ac');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'lorem','et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'orci,','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'pede.','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Fusce','diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nec','pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'faucibus','at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'sit','tortor,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'consequat','auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nec','volutpat. Nulla facilisis. Suspendisse');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Maecenas','aliquet diam. Sed diam lorem, auctor quis, tristique ac,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Proin','in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Sed','est mauris, rhoncus id, mollis');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'dolor.','lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'orci.','pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'laoreet,','risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'semper','amet');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'lorem,','vel, mauris. Integer sem elit, pharetra ut, pharetra sed,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nibh','sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'sit','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'pretium','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'sit','magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ipsum.','arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Proin','Duis risus odio, auctor');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'egestas,','tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'mollis.','mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'pede','eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'posuere','nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'et,','lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'eros','Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'gravida.','fringilla purus mauris a nunc. In at pede. Cras vulputate velit');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nulla','erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'iaculis','auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'In','Maecenas mi felis, adipiscing fringilla, porttitor vulputate,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'rhoncus.','sodales purus, in molestie tortor nibh sit amet orci.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'consectetuer','sit amet ornare lectus justo eu arcu. Morbi sit amet massa.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'et','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'rutrum','sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Vivamus','non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus.');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'interdum','vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Fusce','ut cursus luctus, ipsum leo');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'erat','erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Proin','Nam ac nulla. In tincidunt');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nulla.','nec tellus. Nunc lectus pede,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Praesent','dictum eu,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'dolor.','amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'augue','amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Suspendisse','libero nec ligula consectetuer rhoncus. Nullam velit dui, semper');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Phasellus','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'iaculis','massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Nullam','suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'non','dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'semper','Proin velit. Sed malesuada augue ut');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'nec,','ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'eu','dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'torquent','egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'ornare','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'rutrum,','turpis non enim. Mauris quis turpis vitae purus gravida');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Curabitur','penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'et,','malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,');
INSERT INTO Categories (idCateg,Nomdecategorie,description) VALUES (compteur.nextval,'Morbi','quis turpis vitae purus');