 CREATE TABLE "EMPLOYES" 
   ("IDEMPLOYE" Integer PRIMARY KEY, 
	"NOM" VARCHAR2(100 CHAR), 
	"PRENOM" VARCHAR2(100 CHAR), 
	"FONCTIONEMPLOYE" VARCHAR2(100 CHAR), 
	"TITREDECOURTOISIE" VARCHAR2(100 CHAR), 
	"DATEDENAISSANCE" DATE, 
	"DATEEMBAUCHE" DATE, 
	"ADRESSEEMPLOYE" VARCHAR2(100 CHAR), 
	"VILLEEMPLOYE" VARCHAR2(100 CHAR), 
	"PAYSEMPLOYE" VARCHAR2(100 CHAR), 
	"TELDOMICILE" VARCHAR2(100 CHAR)
   );


INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (1,'Aguirre','Brent','luctus ut, pellentesque eget, dictum placerat,','Mr','03/10/2021','Felitto','Hungary','08 87 56 54 07');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (2,'Cross','Cleo','tincidunt. Donec vitae erat vel','Mme','08/09/2021','Castel Ritaldi','Netherlands','01 57 67 00 88');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (3,'Sawyer','Sebastian','augue ut lacus. Nulla tincidunt, neque vitae semper','Mme','26/02/2020','Lo Espejo','Virgin Islands, United States','02 83 21 38 72');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (4,'Petty','Tyrone','Sed pharetra, felis eget varius ultrices, mauris','Mr','01/11/2021','Limburg a.d. Lahn','Haiti','07 96 59 90 16');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (5,'Perkins','Steven','dui. Fusce diam nunc, ullamcorper eu,','Mme','24/08/2021','Khanewal','Korea, North','04 34 93 47 75');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (6,'Ware','Eaton','ut aliquam iaculis, lacus pede sagittis','Mr','11/03/2020','Sint-Stevens-Woluwe','Cyprus','08 49 54 42 09');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (7,'Hurst','Lisandra','Duis cursus, diam at pretium aliquet, metus urna convallis','Mme','01/07/2020','Sint-Gillis','Bahrain','02 23 22 37 80');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (8,'Shaw','Ferris','nulla. Donec non justo.','Mme','19/05/2021','Vanier','Guernsey','08 28 40 41 66');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (9,'Savage','Elton','Nam ligula','Mr','21/01/2021','Cork','Niue','02 02 06 83 24');
INSERT INTO Employes (IDEMPLOYE,NOM,PRENOM,FONCTIONEMPLOYE,TITREDECOURTOISIE,DATEDENAISSANCE,VILLEEMPLOYE,PAYSEMPLOYE,TELDOMICILE) VALUES (10,'Hughes','Ray','malesuada. Integer id magna et','Mme','09/06/2021','Torno','Belgium','04 64 67 28 15');