 CREATE TABLE "FOURNISSEURS" 
   ("IDFOUR" INTEGER PRIMARY KEY, 
	"SOCIETEFOUR" VARCHAR2(100 CHAR), 
	"CONTACTFOUR" VARCHAR2(100 CHAR), 
	"FONCTIONFOUR" VARCHAR2(100 CHAR), 
	"ADRESSEFOUR" VARCHAR2(100 CHAR), 
	"VILLEFOUR" VARCHAR2(100 CHAR), 
	"REGIONFOUR" VARCHAR2(100 CHAR), 
	"CP" VARCHAR2(100 CHAR), 
	"PAYSFOUR" VARCHAR2(100 CHAR), 
	"TELFOUR" VARCHAR2(100 CHAR), 
	"FAXFOUR" VARCHAR2(100 CHAR)
   ); 

INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (1,'Yen','Lerg','Directeur','Appartement 787-832 Av Rue','Jaipur','MA','Singapore','05 03 17 79 46');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (2,'Nunc','Blaze','Directeur','Appartement 926-832 Ac Rue','Stuttgart','BW','Saint Pierre and Miquelon','02 03 17 79 46');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (3,'non','Troy','Commercial','1076 Nullam Impasse','Desamparados','SJ','Christmas Island','05 33 29 46 42');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (4,'nibh.','Boris','Directeur','CP 514, 6159 Phasellus Av.','Warszawa','MA','France','04 99 65 78 66');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (5,'massa.','Holmes','Administrateur','2941 Blandit Rue','Jaipur','RJ','Singapore','01 11 96 38 95');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (6,'egestas','Kyla','Commercial','364-1935 Lobortis Av.','Raiganj','West Bengal','Romania','08 84 16 39 67');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (7,'Phasellus','Raphael','DRH','177-8582 Litora Rd.','Sereflikoçhisar','Ankara','Norfolk Island','09 05 51 00 13');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (8,'ut','Celeste','DRH','329-2818 Pharetra Ave','Bendigo','Victoria','Libya','04 00 23 21 62');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (9,'quis','Hyatt','Directeur','145-9493 Lacus. Impasse','Onitsha','AN','Iraq','03 23 79 16 93');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (10,'turpis.','Gavin','Commercial','7339 Elit, Av.','Vienna','Wien','Dominica','01 51 18 52 30');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (11,'nisi','Elijah','Administrateur','Appartement 397-3636 Tincidunt. Impasse','Lanark County','ON','Somalia','01 77 10 25 28');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (12,'pede','Eleanor','Administrateur','CP 315, 2143 Sollicitudin Rue','Ussassai','Sardegna','Guinea-Bissau','06 78 93 20 83');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (13,'rutrum.','Maisie','Administrateur','Appartement 543-2571 Velit. Impasse','Colchester','Vermont','Macedonia','03 95 61 45 46');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (14,'dolor','Norman','Directeur','9286 Ornare, Ave','Campos dos Goytacazes','RJ','Argentina','06 59 13 27 99');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (15,'lorem','Lani','Administrateur','Appartement 118-4746 Morbi Rue','Colchane','I','Costa Rica','04 06 13 94 90');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (16,'vitae','Beck','Administrateur','CP 402, 5666 Adipiscing Ave','Vienna','Wien','Pakistan','09 57 27 89 65');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (17,'enim','Emmanuel','Directeur','730-8749 Curabitur Ave','Lakeshore','ON','Israel','02 79 79 11 47');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (18,'ipsum','Athena','Directeur','983-6585 Euismod Avenue','San José de Alajuela','A','Jersey','05 09 73 57 70');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (19,'eu,','Alika','Commercial','2263 Id, Ave','Valéncia','Comunitat Valenciana','Singapore','04 28 59 95 67');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (20,'placerat','Chantale','Administrateur','141-6099 Tempus Avenue','Nässjö','Jönköpings län','Chad','03 82 82 59 73');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (21,'primis','Sybil','Directeur','595-8568 Fringilla Route','Istanbul','Istanbul','Faroe Islands','01 03 10 08 57');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (22,'felis','Leonard','Directeur','CP 195, 7192 Egestas Route','Vienna','Vienna','Czech Republic','07 73 66 04 50');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (23,'amet','Holmes','DRH','Appartement 449-5335 Ligula Chemin','Palma de Mallorca','BA','Greenland','03 05 27 04 65');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (24,'ornare,','Guinevere','Commercial','8303 At, Chemin','Berlin','BE','Uganda','04 90 74 74 29');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (25,'arcu.','Akeem','Directeur','880-8618 Neque. Ave','Konstanz','Baden Württemberg','Macedonia','05 05 09 09 72');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (26,'eleifend','Jared','Commercial','2284 Massa Impasse','Rhayader','Radnorshire','New Caledonia','03 23 27 86 80');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (27,'fringilla','Amity','DRH','CP 622, 499 Aliquet Av.','Steyr','OÖ.','Spain','02 65 51 32 03');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (28,'nec,','Odette','Commercial','152-8696 Neque Avenue','Flin Flon','MB','Czech Republic','06 80 68 75 08');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (29,'dis','Carlos','Directeur','Appartement 453-9814 Sed Impasse','Concepción','San José','Suriname','08 15 78 76 40');
INSERT INTO Fournisseurs (IDFOUR,SOCIETEFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,REGIONFOUR,PAYSFOUR,TELFOUR) VALUES (30,'Cum','Ivana','DRH','2483 Quisque Rue','Kapiti','North Island','Congo, the Democratic Republic of the','06 83 57 42 33');